version: '3.8'

services:

  node:
    image: node:18
    container_name: node
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    tty: true
    command: ["sh", "-c", "npm install && tail -f /dev/null"]


  app:
    build:
      context: ./docker/php
    container_name: php-app
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: curso_php
      MYSQL_USER: vic
      MYSQL_PASSWORD: vic123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
volumes:
  mysql_data:



networks:
  app-network:
    driver: bridge
